# 配置文件示例
server:
  ip: 192.168.1.102
  tcp:
    port: 6666
  http:
    port: 8080

# 服务发现
discovery:
  consul:
    address: 192.168.1.102:8500
    health:
      timeout: 5
      interval: 5
      deregisterCriticalServiceAfter: 30

# 数据库
db:
  mysql:
    host: localhost
    port: 3306
    schema: customer
    username: root
    password: 123456
